import type { Monaco } from "@monaco-editor/react";

export const COMPILERHUB_THEME = "compilerhub-dark";

// Tokyo-Night-inspired palette tuned to our app tokens
export function defineCompilerHubTheme(monaco: Monaco) {
  monaco.editor.defineTheme(COMPILERHUB_THEME, {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "", foreground: "c0caf5" },
      { token: "comment", foreground: "565f89", fontStyle: "italic" },
      { token: "keyword", foreground: "bb9af7" },
      { token: "keyword.control", foreground: "bb9af7" },
      { token: "keyword.directive", foreground: "f7768e" },
      { token: "number", foreground: "ff9e64" },
      { token: "string", foreground: "9ece6a" },
      { token: "string.escape", foreground: "f7768e" },
      { token: "type", foreground: "2ac3de" },
      { token: "type.identifier", foreground: "2ac3de" },
      { token: "identifier", foreground: "c0caf5" },
      { token: "function", foreground: "7aa2f7" },
      { token: "delimiter", foreground: "89ddff" },
      { token: "operator", foreground: "89ddff" },
      { token: "tag", foreground: "f7768e" },
      { token: "attribute.name", foreground: "bb9af7" },
      { token: "attribute.value", foreground: "9ece6a" },
      { token: "variable", foreground: "c0caf5" },
      { token: "variable.predefined", foreground: "f7768e" },
    ],
    colors: {
      "editor.background": "#0b1020",
      "editor.foreground": "#c0caf5",
      "editorLineNumber.foreground": "#3b4261",
      "editorLineNumber.activeForeground": "#7aa2f7",
      "editor.lineHighlightBackground": "#13182b",
      "editor.lineHighlightBorder": "#13182b",
      "editorCursor.foreground": "#bb9af7",
      "editor.selectionBackground": "#283457",
      "editor.inactiveSelectionBackground": "#202840",
      "editor.selectionHighlightBackground": "#1f2540",
      "editor.wordHighlightBackground": "#1f2540",
      "editorIndentGuide.background": "#1a2036",
      "editorIndentGuide.activeBackground": "#2a3158",
      "editorWhitespace.foreground": "#1a2036",
      "editorBracketMatch.background": "#283457",
      "editorBracketMatch.border": "#7aa2f7",
      "editorGutter.background": "#0b1020",
      "scrollbarSlider.background": "#1a203680",
      "scrollbarSlider.hoverBackground": "#2a3158aa",
      "scrollbarSlider.activeBackground": "#7aa2f7aa",
      "minimap.background": "#0b1020",
      "editorWidget.background": "#13182b",
      "editorWidget.border": "#1f2540",
      "editorSuggestWidget.background": "#13182b",
      "editorSuggestWidget.border": "#1f2540",
      "editorSuggestWidget.selectedBackground": "#283457",
      "editorHoverWidget.background": "#13182b",
      "editorHoverWidget.border": "#1f2540",
      "editorError.foreground": "#f7768e",
      "editorWarning.foreground": "#e0af68",
    },
  });
}
